---
os: linux
arch: arm64-graviton2
dist: bionic
language: python
python:
  - 3.8
sudo: required
services:
  - docker

jobs:
  include:
    - stage: build-test-push
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      install:
        - pip install --upgrade pip
        - make venv
      script:
        - set -e
        - make build-all
        - make test
      after_success:
        - bash scripts/after_success.sh

stages:
  - name: build-test-push
    if: branch = main
