version: '3'

volumes:
  pg-data-hub:

services:
  jupyterhub:
    build:
      context: jupyterhub/.
      dockerfile: Dockerfile.chp
    image: illumidesk/jupyterhub:chp
    container_name: jupyterhub
    restart: on-failure
    env_file:
      - .env
    command: >
      jupyterhub --config /srv/jupyterhub/jupyterhub_config.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    ports:
      - 8000:8000
  postgres-hub:
    image: postgres
    env_file:
      - .env
    volumes:
       - pg-data-hub:/var/lib/postgresql/data
