version: '3'

volumes:
  pg-data-kc:
  pg-data-hub:

services:
  nginx:
    build: nginx/.
    image: illumidesk/nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  jupyterhub:
    build: jupyterhub/.
    image: illumidesk/jupyterhub:test
    container_name: jupyterhub
    restart: on-failure
    env_file:
      - .env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./jupyterhub/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py
  postgres-hub:
    image: postgres
    environment:
      POSTGRES_DB: jupyterhub
      POSTGRES_USER: jupyterhub
      POSTGRES_PASSWORD: password
    volumes:
       - pg-data-hub:/var/lib/postgresql/data
