version: '3'

volumes:
  pg-data-hub:

services:
  jupyterhub:
    build:
      context: jupyterhub/.
      dockerfile: Dockerfile.chp
    image: illumidesk/jupyterhub:chp
    container_name: jupyterhub
    restart: on-failure
    env_file:
      - .env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./jupyterhub/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py
  postgres-hub:
    image: postgres
    environment:
      POSTGRES_DB: jupyterhub
      POSTGRES_USER: jupyterhub
      POSTGRES_PASSWORD: password
    volumes:
       - pg-data-hub:/var/lib/postgresql/data
