FROM illumidesk/jupyterhub:latest

USER root

RUN apt-get update \
 && apt-get install npm=6.14.4+ds-1ubuntu2 -y --no-install-recommends\
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

USER "${NB_UID}"

RUN npm install -g configurable-http-proxy@^4.2.0 --no-install-recommends \
 && rm -rf ~/.npm

RUN python3 -m pip install --no-cache notebook==6.3.0
